{
 "title": "SuperSLA",
 "time": { "from": "2019-11-07T14:51:45.852Z", "to": "2019-11-07T15:07:23.118Z" },
 "templating": {
  "list": [
   { "name": "aggregation", "label": "Aggregation", "query": "5s,10s,30s,1m,5m,30m,1h" },
   {
    "name": "transaction",
    "label": "Jmeter Operation",
    "query": "label_values(jmeter_requests, requestName)"
   },
   {
    "name": "transactionGroup",
    "query": "jmeter_requests{requestName=\"$transaction\"}"
   },
   { "name": "gatlingWriteInterval", "query": "5" },
   {
    "name": "GatlingTransaction",
    "label": "Gatling Operation",
    "query": "label_values(groupRequestInfo_sum, group)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total TPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum (rate(jmeter_requests{requestName=~\".+XX.+\"}[10s]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(rate(groupRequestInfo_sum[25s]))"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(rate(jmeter_response_time_sum{requestName=~\".+XX.+\"}[10s])/rate(jmeter_response_time_count{requestName=~\".+XX.+\"}[10s]))"
      },
      {
       "expr": "avg(jmeter_response_time{requestName=~\".+XX.+\"})",
       "legendFormat": "90pct"
      },
      {
       "expr": "avg(rate(groupRequestInfo_sum[25s])/rate(groupRequestInfo_count[25s]))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(groupRequestInfo_bucket[25s])) by (le))",
       "legendFormat": "90pct"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "total_started_users", "legendFormat": "Thread count" }
     ]
    },
    {
     "title": "Aggregate Report",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "sum(\nmax_over_time(jmeter_requests{requestName=~\".+XX.+\"}[${__range_s}s])\n- min_over_time(jmeter_requests{requestName=~\".+XX.+\"}[${__range_s}s])\n) by (runId, requestName)",
       "legendFormat": "requests"
      },
      {
       "expr": "sum(\nmax_over_time(groupRequestInfo_count[${__range_s}s]) \n- min_over_time(groupRequestInfo_count[${__range_s}s])\n) by (group)",
       "legendFormat": "requests"
      },
      {
       "expr": "avg(\n(max_over_time(jmeter_response_time_sum{requestName=~\".+XX.+\"}[${__range_s}s]) - min_over_time(jmeter_response_time_sum{requestName=~\".+XX.+\"}[${__range_s}s]))\n/ (max_over_time(jmeter_response_time_count{requestName=~\".+XX.+\"}[${__range_s}s]) - min_over_time(jmeter_response_time_count{requestName=~\".+XX.+\"}[${__range_s}s]))\n) by (runId, requestName)",
       "legendFormat": "avg"
      },
      {
       "expr": "avg(\n(max_over_time(groupRequestInfo_sum[${__range_s}s]) - min_over_time(groupRequestInfo_sum[${__range_s}s]))\n/ (max_over_time(groupRequestInfo_count[${__range_s}s]) - min_over_time(groupRequestInfo_count[${__range_s}s]))\n) by (group)",
       "legendFormat": "avg"
      },
      {
       "expr": "avg(\navg_over_time(jmeter_response_time{requestName=~\".+XX.+\"}[${__range_s}s])\n) by (runId, requestName)",
       "legendFormat": "90pct"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(groupRequestInfo_bucket[${__range_s}s])) by (le))",
       "legendFormat": "90pct"
      },
      {
       "expr": "sum(\nmax_over_time(groupRequestInfo_count{oK=\"KO\"}[${__range_s}s])\n- min_over_time(groupRequestInfo_count{oK=\"KO\"}[${__range_s}s])\n) by (group)\n/ sum(\nmax_over_time(groupRequestInfo_count[${__range_s}s])\n- min_over_time(groupRequestInfo_count[${__range_s}s])\n) by (group)",
       "legendFormat": "errors"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Rate",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(\nmax_over_time(groupRequestInfo_count{oK=\"KO\"}[${__range_s}s])\n- min_over_time(groupRequestInfo_count{oK=\"KO\"}[${__range_s}s])\n)\n/ sum(\nmax_over_time(groupRequestInfo_count[${__range_s}s])\n- min_over_time(groupRequestInfo_count[${__range_s}s])\n)"
      }
     ]
    },
    {
     "title": "Errors per Transaction",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 4, "y": 2 },
     "targets": [
      {
       "expr": "sum(\nmax_over_time(jmeter_requests{requestName=~\".+XX.+\", requestStatus=\"FAIL\"}[${__range_s}s])\n- min_over_time(jmeter_requests{requestName=~\".+XX.+\", requestStatus=\"FAIL\"}[${__range_s}s])\n) by (runId, requestName)"
      },
      {
       "expr": "sum(\nmax_over_time(groupRequestInfo_count{oK=\"KO\"}[${__range_s}s])\n- min_over_time(groupRequestInfo_count{oK=\"KO\"}[${__range_s}s])\n) by (group)\n",
       "legendFormat": "errors"
      }
     ]
    },
    {
     "title": "Error Info",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 2 },
     "targets": [
      {
       "expr": "sum(\nmax_over_time(jmeter_requests{requestName!~\".+XX.+\", requestStatus=\"FAIL\"}[${__range_s}s])\n- min_over_time(jmeter_requests{requestName!~\".+XX.+\", requestStatus=\"FAIL\"}[${__range_s}s])\n) by (runId, responseCode, responseMessage)"
      },
      {
       "expr": "sum(\nmax_over_time(requests_latency_secondsHistogram_count{oK=\"KO\"}[${__range_s}s])\n- min_over_time(requests_latency_secondsHistogram_count{oK=\"KO\"}[${__range_s}s])\n) by (error, responseCode)"
      }
     ]
    },
    {
     "title": "Error Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate(requests_latency_secondsHistogram_count{oK=~\"KO\"}[1m])) by (responseCode)",
       "legendFormat": "Response Code = {{responseCode}}"
      },
      {
       "expr": "sum (rate(jmeter_requests{requestStatus=\"FAIL\"}[1m])) by(responseCode)",
       "legendFormat": "Response Code = {{responseCode}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Jmeter Operation - $transaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sent/Received",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "decbytes" }
     ]
    },
    {
     "title": "Transaction Info",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "sum(\nmax_over_time(jmeter_requests{requestName=~\"^$transactionGroup\"}[${__range_s}s])\n- min_over_time(jmeter_requests{requestName=~\"^$transactionGroup\"}[${__range_s}s])\n) by (runId, requestName, responseCode, responseMessage)"
      }
     ]
    },
    {
     "title": "TPS - $transaction",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jmeter_requests{requestName=\"$transaction\"}[10s])) by (requestStatus)",
       "legendFormat": "{{requestStatus}}"
      }
     ]
    },
    {
     "title": "Response Time - $transaction",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jmeter_response_time_sum{requestName=\"$transaction\"}[10s])/rate(jmeter_response_time_count{requestName=\"$transaction\"}[10s]))",
       "legendFormat": "avg"
      },
      {
       "expr": "sum(jmeter_response_time{requestName=\"$transaction\"})",
       "legendFormat": "90pct"
      }
     ]
    }
   ]
  },
  {
   "title": "Gatling Operation -  $GatlingTransaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "GatlingTransaction",
   "collapsed": true,
   "panels": [
    {
     "title": "TPS - $GatlingTransaction",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(requests_latency_secondsHistogram_count{group=\"$GatlingTransaction\"}[25s])) by (oK)"
      }
     ]
    },
    {
     "title": "Response Time - $GatlingTransaction",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rate(groupRequestInfo_sum{group=\"$GatlingTransaction\"}[25s])/rate(groupRequestInfo_count{group=\"$GatlingTransaction\"}[25s]))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(groupRequestInfo_bucket{group=\"$GatlingTransaction\"}[25s])) by (le))",
       "legendFormat": "90pct"
      }
     ]
    },
    {
     "title": "Transaction Info",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(\nmax_over_time(requests_latency_secondsHistogram_count{group=\"$GatlingTransaction\", responseCode!=\"0\"}[${__range_s}s]) \n- min_over_time(requests_latency_secondsHistogram_count{group=\"$GatlingTransaction\", responseCode!=\"0\"}[${__range_s}s])\n) by (metric, responseCode)"
      }
     ]
    },
    {
     "title": "Transaction Errors Info",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum(\nmax_over_time(requests_latency_secondsHistogram_count{group=\"$GatlingTransaction\", responseCode!=\"0\", error!=\"\"}[${__range_s}s]) \n- min_over_time(requests_latency_secondsHistogram_count{group=\"$GatlingTransaction\", responseCode!=\"0\", error!=\"\"}[${__range_s}s])\n) by (metric, error, responseCode)"
      }
     ]
    },
    {
     "title": "% Errors By Requests",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum(\nmax_over_time(requests_latency_secondsHistogram_count{group=\"$GatlingTransaction\", oK=\"KO\"}[${__range_s}s])\n- min_over_time(requests_latency_secondsHistogram_count{group=\"$GatlingTransaction\", oK=\"KO\"}[${__range_s}s])\n) by (metric)\n/ sum(\nmax_over_time(requests_latency_secondsHistogram_count{group=\"$GatlingTransaction\"}[${__range_s}s])\n- min_over_time(requests_latency_secondsHistogram_count{group=\"$GatlingTransaction\"}[${__range_s}s])\n) by (metric)",
       "legendFormat": "{{metric}}"
      }
     ]
    }
   ]
  }
 ]
}